name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Kudos DOER!🥳 You just created your first Issue!🌟 One of our Repo Mainatiner, will reach out soon!💥 Happy Hacking!🤖'
        pr-message: 'Wohoo!🥳 You just made your first PR.✔️ A developer''s time is of utmost importance.⏲ We will soon assign a reviewer, who will reach you out soon!💥 Happy Hacking!🤖'
